#!/usr/bin/env node
// agix-bench.mjs — the Agix research/benchmark pipeline runner (North Star pillar P2).
//
// "Proven by our own research" needs a *repeatable* proof loop, not one-off
// measurements. This is that loop, made first-class: a runner that discovers
// probes, runs each, and emits a reproducible, narrator-shaped report (a
// deterministic data layer an LLM TL;DR can be prepended to — per the
// narrator-pattern doctrine the internal proving ground proved highest-ROI).
//
// A probe is a self-describing unit in bench/probes/*.mjs that default-exports:
//   { name, question, reproduce, async run() -> {
//       skipped?: bool, note?: string,
//       summary: string,                       // one-line headline
//       rows: [{ metric, value }],             // the data table
//       meta?: object,                         // params / provenance
//   } }
//
// Usage:
//   node bench/agix-bench.mjs                  # run all probes, write report
//   node bench/agix-bench.mjs token-economics  # run one probe by name
//
// Output:
//   bench/results/<YYYY-MM-DD>.json            # structured results (machine)
//   wiki/research/benchmarks/<YYYY-MM-DD>.md   # the report (human; narrator data layer)

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');
const probesDir = path.join(__dirname, 'probes');

// --- stats helpers (exported for sample-based probes) -----------------------
export function stats(samples) {
  const s = [...samples].sort((a, b) => a - b);
  const n = s.length;
  const sum = s.reduce((a, b) => a + b, 0);
  const pct = (p) => s[Math.min(n - 1, Math.floor(n * p))];
  return { n, mean: sum / n, p50: pct(0.5), p99: pct(0.99), max: s[n - 1] };
}

function today() {
  // plain Node CLI (not a Workflow script) — Date is available here.
  return new Date().toISOString().slice(0, 10);
}

async function loadProbes(filters) {
  if (!fs.existsSync(probesDir)) return [];
  // `filters` is a (possibly empty) set of probe names. Empty = run all.
  // Accepting multiple names lets you run a focused, no-model-spend subset
  // (e.g. `node bench/agix-bench.mjs bus-latency bus-throughput bus-throughput-p2p`).
  const wanted = filters && filters.size ? filters : null;
  const files = fs.readdirSync(probesDir).filter((f) => f.endsWith('.mjs')).sort();
  const probes = [];
  for (const f of files) {
    const mod = await import(path.join(probesDir, f));
    const probe = mod.default;
    if (!probe?.name) continue;
    if (wanted && !wanted.has(probe.name)) continue;
    probes.push(probe);
  }
  return probes;
}

function renderReport(date, results) {
  const lines = [];
  lines.push('---');
  lines.push(`title: "Agix benchmark report — ${date}"`);
  lines.push('type: source');
  lines.push('domain: research, benchmark, agix-aos');
  lines.push(`created: ${date}`);
  lines.push('status: active');
  lines.push('tags: [benchmark, proof-engine, north-star-p2]');
  lines.push('generated_by: bench/agix-bench.mjs');
  lines.push('---');
  lines.push('');
  lines.push(`# Agix benchmark report — ${date}`);
  lines.push('');
  lines.push('> **Narrator data layer.** This file is deterministically generated by');
  lines.push('> `bench/agix-bench.mjs`. A narrator routine may prepend a TL;DR + anomaly');
  lines.push('> callouts ABOVE this line; it must never edit the numbers below (per the');
  lines.push('> narrator-pattern doctrine — the data layer is independently verifiable).');
  lines.push('');
  lines.push('<!-- NARRATOR-TLDR: (prepend narrative summary here; leave the data intact) -->');
  lines.push('');
  for (const r of results) {
    lines.push(`## ${r.name}`);
    lines.push('');
    lines.push(`**Question:** ${r.question}`);
    lines.push('');
    if (r.skipped) {
      lines.push(`_Skipped: ${r.note || 'no reason given'}_`);
      lines.push('');
      continue;
    }
    lines.push(`**Result:** ${r.summary}`);
    lines.push('');
    lines.push('| Metric | Value |');
    lines.push('|---|---|');
    for (const row of r.rows || []) lines.push(`| ${row.metric} | ${row.value} |`);
    lines.push('');
    if (r.meta && Object.keys(r.meta).length) {
      lines.push(`**Provenance / params:** \`${JSON.stringify(r.meta)}\``);
      lines.push('');
    }
    lines.push(`**Reproduce:** \`${r.reproduce}\``);
    lines.push('');
  }
  lines.push('---');
  lines.push('');
  lines.push('_Generated by the Agix research/benchmark pipeline (North Star P2). Add a probe:');
  lines.push('drop a `bench/probes/<name>.mjs` default-exporting `{name, question, reproduce, run()}`._');
  lines.push('');
  return lines.join('\n');
}

async function main() {
  const filters = new Set(process.argv.slice(2));
  const date = today();
  const probes = await loadProbes(filters);
  if (!probes.length) {
    console.error(filters.size ? `no probe(s) matched: ${[...filters].join(', ')}` : 'no probes found in bench/probes/');
    process.exit(1);
  }
  console.log(`agix-bench: running ${probes.length} probe(s)\n`);
  const results = [];
  for (const probe of probes) {
    process.stdout.write(`• ${probe.name} ... `);
    try {
      const out = await probe.run({ stats, repoRoot });
      results.push({ name: probe.name, question: probe.question, reproduce: probe.reproduce, ...out });
      console.log(out.skipped ? `skipped (${out.note})` : 'ok');
    } catch (e) {
      results.push({ name: probe.name, question: probe.question, reproduce: probe.reproduce, skipped: true, note: `error: ${e.message}` });
      console.log(`error: ${e.message}`);
    }
  }

  // write structured JSON
  const resultsDir = path.join(__dirname, 'results');
  fs.mkdirSync(resultsDir, { recursive: true });
  const jsonPath = path.join(resultsDir, `${date}.json`);
  fs.writeFileSync(jsonPath, JSON.stringify({ date, results }, null, 2) + '\n');

  // write the markdown report (narrator data layer)
  const reportDir = path.join(repoRoot, 'wiki', 'research', 'benchmarks');
  fs.mkdirSync(reportDir, { recursive: true });
  const mdPath = path.join(reportDir, `${date}.md`);
  fs.writeFileSync(mdPath, renderReport(date, results));

  console.log(`\nwrote ${path.relative(repoRoot, jsonPath)}`);
  console.log(`wrote ${path.relative(repoRoot, mdPath)}`);
}

main();
